(() => {
  const API_BASE = (window.CONFIG && window.CONFIG.API_BASE_URL) || "https://sorgulen-backend-2.onrender.com/api";
  const KEY_STORAGE = "sorgulen_admin_key";
  const timeTools = window.SorgulenWorkOrderTime;
  const el = (id) => document.getElementById(id);
  const focusContent=el("focusContent"), taskList=el("taskList"), latestBookings=el("latestBookings"), homeStatus=el("homeStatus"), aiSummary=el("aiSummary");
  let home=null, activeProject=null, serverOffset=0, busy=false, quickType=null, confirmRun=null;

  const escapeHtml=(v)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
  const fmtDate=(value)=>{ if(!value)return ""; const d=new Date(`${value}T12:00:00`); return new Intl.DateTimeFormat("no-NO",{timeZone:"Europe/Oslo",weekday:"short",day:"numeric",month:"short"}).format(d); };
  const fmtTime=(value)=>value?new Intl.DateTimeFormat("no-NO",{timeZone:"Europe/Oslo",hour:"2-digit",minute:"2-digit"}).format(new Date(value)):"";
  const fmtDuration=(seconds)=>{const s=Math.max(0,Math.floor(Number(seconds)||0));return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,"0")).join(":");};
  function key(){return (localStorage.getItem(KEY_STORAGE)||"").trim();}
  async function api(path,options={}){const res=await fetch(`${API_BASE}${path}`,{...options,headers:{"Content-Type":"application/json","x-admin-key":key(),...(options.headers||{})}});const data=await res.json().catch(()=>null);if(data?.serverTime)serverOffset=new Date(data.serverTime).getTime()-Date.now();if(res.status===401||res.status===403){localStorage.removeItem(KEY_STORAGE);location.href="login.html";throw new Error("Logg inn på nytt.");}if(!res.ok)throw new Error(data?.error||`API-feil ${res.status}`);return data;}
  function setStatus(text,type=""){homeStatus.textContent=text||"";homeStatus.className=`home-status ${type}`.trim();}
  function currentSeconds(order){return timeTools?timeTools.calculateWorkSeconds(order,Date.now()+serverOffset):Number(order.currentWorkSeconds||0);}
  function projectStats(order){const expenses=order.additionalCosts||[],materials=order.materials||[],notes=order.projectNotes||[];const expenseTotal=expenses.reduce((sum,item)=>sum+(Number(item.amount)||0),0);const money=new Intl.NumberFormat("no-NO",{style:"currency",currency:"NOK",maximumFractionDigits:0}).format(expenseTotal);return `<div class="project-stats"><span>${order.workIntervals?.length||0} økter</span><span>${money} utgifter</span><span>${materials.length} materialer</span><span>${notes.length} notater</span></div>`;}
  function quickButtons(order){return `<div class="quick-actions"><button class="quick-action" data-quick="expense" data-id="${escapeHtml(order._id)}">+ Utgift</button><button class="quick-action" data-quick="material" data-id="${escapeHtml(order._id)}">+ Materiale</button><button class="quick-action" data-quick="note" data-id="${escapeHtml(order._id)}">+ Notat</button></div>`;}
  function renderFocus(){
    const active=home.activeWorkOrder;
    if(active){activeProject=active;const isPaused=active.status==="paused";focusContent.className="home-card focus-card is-active";focusContent.innerHTML=`<div class="focus-top"><div><p class="eyebrow">Pågår nå</p><h2 id="focusTitle" class="focus-name">${escapeHtml(active.customerSnapshot?.name||"Ukjent kunde")}</h2><p class="focus-service">${escapeHtml(active.serviceName)}</p></div><span class="status-pill ${isPaused?"paused":"active"}">${isPaused?"Pauset":"Aktiv"}</span></div><div class="timer" data-live-timer>${fmtDuration(currentSeconds(active))}</div><p class="focus-meta">${isPaused?"Pausen regnes ikke som arbeidstid":`Startet ${fmtTime(active.workIntervals?.at(-1)?.startedAt||active.startedAt)}`}</p>${projectStats(active)}<div class="main-actions"><button class="primary-action" data-action="${isPaused?"resume":"pause"}" data-id="${escapeHtml(active._id)}">${isPaused?"Fortsett":"Pause"}</button><button class="secondary-action" data-confirm="stop" data-id="${escapeHtml(active._id)}">Avslutt økt</button></div>${quickButtons(active)}`;return;}
    const ongoing=home.ongoingProject;
    if(ongoing){activeProject=ongoing;focusContent.className="home-card focus-card";focusContent.innerHTML=`<div class="focus-top"><div><p class="eyebrow">Pågående prosjekt</p><h2 id="focusTitle" class="focus-name">${escapeHtml(ongoing.customerSnapshot?.name||"Ukjent kunde")}</h2><p class="focus-service">${escapeHtml(ongoing.serviceName)}</p></div><span class="status-pill">Mellom økter</span></div><p class="focus-meta" style="margin:20px 0 10px">Registrert tid: <strong>${fmtDuration(currentSeconds(ongoing))}</strong></p>${projectStats(ongoing)}<div class="main-actions"><button class="primary-action" data-action="resume" data-session="work" data-id="${escapeHtml(ongoing._id)}">Fortsett arbeid</button><button class="secondary-action" data-action="resume" data-session="purchase" data-id="${escapeHtml(ongoing._id)}">Start innkjøpstid</button><button class="secondary-action" data-action="resume" data-session="transport" data-id="${escapeHtml(ongoing._id)}">Start transporttid</button><button class="secondary-action danger-action" data-confirm="complete" data-id="${escapeHtml(ongoing._id)}">Fullfør prosjekt</button></div>${quickButtons(ongoing)}`;return;}
    activeProject=null;const planned=home.nextWorkOrder;
    if(planned){focusContent.className="home-card focus-card";focusContent.innerHTML=`<div class="focus-top"><div><p class="eyebrow">Neste oppdrag</p><h2 id="focusTitle" class="focus-name">${escapeHtml(planned.customerSnapshot?.name||"Ukjent kunde")}</h2><p class="focus-service">${escapeHtml(planned.serviceName)}</p></div><span class="status-pill">Planlagt</span></div><p class="focus-meta" style="margin:20px 0">${escapeHtml(fmtDate(planned.jobDate))}${planned.customerSnapshot?.address?`<br>${escapeHtml(planned.customerSnapshot.address)}`:""}</p><button class="primary-action" data-action="start" data-session="work" data-id="${escapeHtml(planned._id)}">Start oppdrag</button>`;return;}
    const b=home.nextBooking;
    if(b){focusContent.className="home-card focus-card";focusContent.innerHTML=`<div class="focus-top"><div><p class="eyebrow">Neste oppdrag</p><h2 id="focusTitle" class="focus-name">${escapeHtml(b.customerName)}</h2><p class="focus-service">${escapeHtml(b.serviceName)}</p></div><span class="status-pill">${escapeHtml(b.status==="pending"?"Venter":"Planlagt")}</span></div><p class="focus-meta" style="margin:20px 0">${escapeHtml(fmtDate(b.date))} kl. ${escapeHtml(b.time||"")}${b.customerAddress?`<br>${escapeHtml(b.customerAddress)}`:""}</p><a class="primary-action" style="display:inline-grid;place-items:center;text-decoration:none" href="oppdrag.html?bookingId=${encodeURIComponent(b._id)}">Klargjør oppdrag</a>`;return;}
    focusContent.className="home-card focus-card";focusContent.innerHTML=`<p class="eyebrow">Oppdrag</p><h2 id="focusTitle">Ingen aktive eller kommende oppdrag</h2><p class="focus-meta" style="margin:12px 0 18px">Du kan opprette et nytt oppdrag når du trenger det.</p><a class="primary-action" style="display:inline-grid;place-items:center;text-decoration:none" href="oppdrag.html">Opprett oppdrag</a>`;
  }
  function renderTasks(){const tasks=(home.overview?.tasks||[]).filter((task)=>!(home.activeWorkOrder&&String(task.href||"").includes(home.activeWorkOrder._id)));if(!tasks.length){taskList.innerHTML='<div class="empty-home">Ingen ting krever handling akkurat nå.</div>';return;}taskList.innerHTML=tasks.slice(0,8).map(t=>`<div class="task-item"><span class="priority-dot ${escapeHtml(t.priority)}"></span><div><h3>${escapeHtml(t.title)}</h3><p>${escapeHtml(t.detail||"")}${t.ageDays?` · ${t.ageDays} dager`:""}</p></div><a class="task-action" href="${escapeHtml(t.href||"hjem.html")}">Åpne</a></div>`).join("");}
  function renderBookings(){const list=home.latestBookings||[];if(!list.length){latestBookings.innerHTML='<div class="empty-home">Ingen bookinger registrert ennå.</div>';return;}latestBookings.innerHTML=list.map(b=>`<a class="booking-item" href="order-detail.html?id=${encodeURIComponent(b._id)}"><div><h3>${escapeHtml(b.customerName)}</h3><p>${escapeHtml(b.serviceName)} · ${escapeHtml(fmtDate(b.date))} kl. ${escapeHtml(b.time||"")}</p></div><span class="status-pill">${escapeHtml(b.status==="pending"?"Venter":b.status==="planned"?"Planlagt":b.status==="done"?"Utført":"Kansellert")}</span></a>`).join("");}
  async function load(show=true){if(show)setStatus("Henter dagens oversikt…");home=await api("/admin/assistant/home");renderFocus();renderTasks();renderBookings();setStatus("");loadAi();}
  async function loadAi(){let cached=null;try{cached=JSON.parse(sessionStorage.getItem("sorgulen_ai_home")||"null");}catch(_){sessionStorage.removeItem("sorgulen_ai_home");}if(cached&&Date.now()-cached.at<600000){showAi(cached.text);return;}try{const data=await api("/admin/assistant/summary",{method:"POST",body:"{}"});if(data.summary){sessionStorage.setItem("sorgulen_ai_home",JSON.stringify({at:Date.now(),text:data.summary}));showAi(data.summary);}}catch(_){aiSummary.classList.add("hidden");}}
  function showAi(text){aiSummary.textContent=text;aiSummary.classList.remove("hidden");}
  async function action(id,action,sessionType){if(busy)return;busy=true;setStatus(action==="pause"?"Pauser…":action==="stop"?"Avslutter økten…":"Starter økten…");try{await api(`/admin/work-orders/${encodeURIComponent(id)}/action`,{method:"POST",body:JSON.stringify({action,sessionType})});await load(false);}catch(err){setStatus(err.message,"error");}finally{busy=false;}}
  function openQuick(type,id){quickType={type,id};el("quickError").textContent="";const fields={expense:`<div class="quick-field"><label for="qAmount">Beløp</label><input id="qAmount" name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" required autofocus></div><div class="quick-field"><label for="qDescription">Hva gjelder kjøpet?</label><input id="qDescription" name="description" maxlength="500" required></div><div class="quick-field"><label for="qReceipt">Kvittering (valgfritt)</label><input id="qReceipt" name="receipt" type="file" accept="image/jpeg,image/png,image/webp,image/heic" capture="environment"></div>`,material:`<div class="quick-field"><label for="qItem">Materiale</label><input id="qItem" name="item" maxlength="300" required autofocus></div><div class="quick-field"><label for="qQuantity">Antall</label><input id="qQuantity" name="quantity" type="number" min="0.01" step="0.01" inputmode="decimal" value="1" required></div><div class="quick-field"><label for="qPrice">Pris per stk. (valgfritt)</label><input id="qPrice" name="unitPrice" type="number" min="0.01" step="0.01" inputmode="decimal"></div><div class="quick-field"><label for="qComment">Kommentar (valgfritt)</label><input id="qComment" name="comment" maxlength="500"></div>`,note:`<div class="quick-field"><label for="qText">Notat</label><textarea id="qText" name="text" maxlength="2000" required autofocus></textarea></div>`};el("quickTitle").textContent=type==="expense"?"Ny utgift":type==="material"?"Nytt materiale":"Nytt notat";el("quickFields").innerHTML=fields[type];el("quickModal").classList.remove("hidden");}
  const fileData=(file)=>new Promise((resolve,reject)=>{if(!file)return resolve(null);const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error("Kunne ikke lese bildet"));reader.readAsDataURL(file);});
  el("quickForm").addEventListener("submit",async(e)=>{e.preventDefault();if(busy||!quickType)return;const form=new FormData(e.currentTarget),type=quickType.type;let payload=Object.fromEntries(form.entries());delete payload.receipt;try{busy=true;el("quickSave").disabled=true;el("quickError").textContent="";if(type==="expense"){const file=el("qReceipt")?.files?.[0];if(file&&file.size>12*1024*1024)throw new Error("Kvitteringsbildet er for stort (maks 12 MB).");payload.receiptImage=await fileData(file);}await api(`/admin/work-orders/${encodeURIComponent(quickType.id)}/${type==="expense"?"expenses":type==="material"?"materials":"notes"}`,{method:"POST",body:JSON.stringify(payload)});el("quickModal").classList.add("hidden");e.currentTarget.reset();await load(false);}catch(err){el("quickError").textContent=err.message;}finally{busy=false;el("quickSave").disabled=false;}});
  document.addEventListener("click",(e)=>{const q=e.target.closest("[data-quick]");if(q){openQuick(q.dataset.quick,q.dataset.id);return;}const a=e.target.closest("[data-action]");if(a){action(a.dataset.id,a.dataset.action,a.dataset.session);return;}const c=e.target.closest("[data-confirm]");if(c){const operation=c.dataset.confirm;confirmRun=()=>action(c.dataset.id,operation);el("confirmTitle").textContent=operation==="stop"?"Avslutte arbeidsøkten?":"Fullføre prosjektet?";el("confirmText").textContent=operation==="stop"?"Tiden lagres. Prosjektet beholdes og kan fortsettes senere.":"All tid, utgifter, materialer og notater bevares. Prosjektet blir klart til fakturering.";el("confirmModal").classList.remove("hidden");}});
  el("closeQuick").addEventListener("click",()=>el("quickModal").classList.add("hidden"));el("confirmCancel").addEventListener("click",()=>el("confirmModal").classList.add("hidden"));el("confirmOk").addEventListener("click",()=>{el("confirmModal").classList.add("hidden");confirmRun?.();});el("refreshBtn").addEventListener("click",()=>load().catch(err=>setStatus(err.message,"error")));el("logoutBtn").addEventListener("click",()=>localStorage.removeItem(KEY_STORAGE));
  setInterval(()=>{const timer=document.querySelector("[data-live-timer]");if(timer&&home?.activeWorkOrder)timer.textContent=fmtDuration(currentSeconds(home.activeWorkOrder));},1000);
  load().catch(err=>{focusContent.innerHTML='<div class="empty-home">Kunne ikke hente oppdrag.</div>';taskList.innerHTML='<div class="empty-home">Kunne ikke hente gjøremål.</div>';latestBookings.innerHTML='<div class="empty-home">Kunne ikke hente bookinger.</div>';setStatus(err.message,"error");});
})();
