(()=>{
  const API=(window.CONFIG&&window.CONFIG.API_BASE_URL)||"https://sorgulen-backend-2.onrender.com/api",KEY="sorgulen_admin_key",el=(id)=>document.getElementById(id);
  const content=el("customerContent"),status=el("customerStatus"),search=el("customerSearch"),modal=el("customerModal"),form=el("customerForm");let timer;
  const esc=(v)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
  async function api(path,opt={}){const response=await fetch(`${API}${path}`,{...opt,headers:{"content-type":"application/json","x-admin-key":localStorage.getItem(KEY)||"",...(opt.headers||{})}}),data=await response.json().catch(()=>null);if(response.status===401||response.status===403){localStorage.removeItem(KEY);location.href="login.html";throw new Error("Logg inn på nytt");}if(!response.ok)throw Object.assign(new Error(data?.error||"Kunne ikke hente data"),{data});return data;}
  function render(list){content.innerHTML=list.length?list.map((customer)=>`<a class="customer-card" href="kunde.html?id=${encodeURIComponent(customer._id)}"><div><h2>${esc(customer.name)}</h2><p>${esc([customer.phone,customer.email,customer.address].filter(Boolean).join(" · ")||"Ingen kontaktinformasjon")}</p></div><span>Åpne</span></a>`).join(""):'<p class="empty-state">Ingen kunder funnet.</p>';}
  async function load(){status.textContent="Laster…";try{const data=await api(`/admin/customers?q=${encodeURIComponent(search.value.trim())}`);render(data.customers||[]);status.textContent="";}catch(error){status.textContent=error.message;status.className="status-message error";}}
  search.addEventListener("input",()=>{clearTimeout(timer);timer=setTimeout(load,250);});el("newCustomerBtn").onclick=()=>modal.classList.remove("hidden");el("closeCustomerModal").onclick=()=>modal.classList.add("hidden");
  form.addEventListener("submit",async(event)=>{event.preventDefault();const button=form.querySelector("button[type=submit]");button.disabled=true;el("customerError").textContent="";try{const data=await api("/admin/customers",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(form)))});location.href=`kunde.html?id=${encodeURIComponent(data.customer._id)}`;}catch(error){el("customerError").textContent=error.message;}finally{button.disabled=false;}});
  el("logoutBtn").onclick=()=>localStorage.removeItem(KEY);load();
})();
